import NNP_NET

# Initialize needs to be called first. Possible arguments with defaults are:
# smoothing = 3,
# theta = 0.25,
# gpu = false,
# perplexity = 40,
# embeddingSize = 50,
# subgraphSize = 10000,
# pmdsPivots = 250,
# outputDimensions = 2,
# batchSize = 64,
# trainingEpochs = 40
NNP_NET.initialize()

# Either load a graph from a file
g = NNP_NET.loadGraph("TestGraphs/dwt_1005.mtx")

# Or initialize using the following functions
# g = NNP_NET.initializeGraph(4)
# NNP_NET.addEdge(g, 0, 1)
# NNP_NET.addEdge(g, 0, 2)
# NNP_NET.addEdge(g, 0, 3, 0.5)
# NNP_NET.addEdge(g, 1, 2)
# NNP_NET.addEdge(g, 2, 3)

# Run one of the possible graph drawing methods
NNP_NET.NNP_NET(g)
#NNP_NET.PMDS(g)
#NNP_NET.tsNET(g)
#NNP_NET.tsNETStar(g)

# Get the positions generated by the graph drawing method
print(NNP_NET.getEmbedding(g))

# Save the results to a file
NNP_NET.saveGraph("TestGraphs/dwt_1005_out.vna", g)

